{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "novnc-vm.fullname" . }}-novnc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "novnc-vm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "novnc-vm.fullname" . }}-novnc
subjects:
  - kind: ServiceAccount
    name: {{ include "novnc-vm.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
