apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "convex.backend.fullname" . }}
  labels:
    {{- include "convex.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "convex.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "convex.backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "convex.backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "convex.backend.name" $ }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- with .Values.environment }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.cnpg.enabled }}
            - name: CNPG_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "convex.backend.cnpg.name" . }}-app
                  key: user
            - name: CNPG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "convex.backend.cnpg.name" . }}-app
                  key: password
            - name: CNPG_HOST
              value: "{{ include "convex.backend.cnpg.name" . }}-rw.{{ .Release.Namespace }}"
            - name: POSTGRES_URL
              value: "postgresql://$(CNPG_USER):$(CNPG_PASSWORD)@$(CNPG_HOST):5432"
            - name: PG_CA_FILE
              value: "/etc/secrets/ca/ca.crt"
            {{- end }}
            - name: CONVEX_CLOUD_ORIGIN
              value: https://{{ .Values.ingress.host }}
            - name: CONVEX_SITE_ORIGIN
              value: https://{{ .Values.ingress.host }}/http
            - name: INSTANCE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "convex.secret.backend" . }}
                  key: instance_secret
          livenessProbe:
            httpGet:
              path: /version
              port: 3210
            initialDelaySeconds: 10
            periodSeconds: 5
          ports:
            - name: http
              containerPort: 3210
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /convex/data
              name: convex-data
            {{- if .Values.cnpg.enabled }}
            - mountPath: /etc/secrets/ca
              name: cnpg-ca
            {{- end }}
            {{- with .Values.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: convex-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "convex.backend.fullname" . }}-pvc
          {{- else }}
          emptyDir:
            medium: ""
          {{- end }}
        {{- if .Values.cnpg.enabled }}
        - name: cnpg-ca
          secret:
            secretName: {{ include "convex.backend.cnpg.name" . }}-ca
            defaultMode: 0600
        {{- end }}
        {{- with .Values.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        