ingress:
  enabled: true
  className: "traefik"
  annotations: {
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure",
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  }
  tls: "cloudbeaver-tls"
  host: cloudbeaver.example.com

resources:
  requests:
    cpu: "1"
    memory: "1024Mi"
  limits:
    cpu: "1"
    memory: "1024Mi"