nameOverride: ""
fullnameOverride: ""

image:
  repository: directus/directus
  pullPolicy: IfNotPresent
  tag: ""

extraEnvVars: []

ingress:
  className: ""
  annotations: {}
  directus:
    host: directus.example.com

storage: 
  directus:
    storageClassName: ""
    volumeName: ""
    accessMode: "ReadWriteOnce"
    request: "50Gi"

resources:
  directus:
    requests:
      cpu: "1"
      memory: 1024Mi
    limits:
      cpu: "2"
      memory: 2048Mi

admin:
  username: example@test.com
