apiVersion: v1
kind: Service
metadata:
  name: {{ include "forgejo.fullname" . }}-http
  labels:
    {{- include "forgejo.labels" . | nindent 4 }}
    app.kubernetes.io/component: http
spec:
  type: {{ .Values.service.http.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.http.type "NodePort") .Values.service.http.nodePort }}
      nodePort: {{ .Values.service.http.nodePort }}
      {{- end }}
  selector:
    {{- include "forgejo.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "forgejo.fullname" . }}-ssh
  labels:
    {{- include "forgejo.labels" . | nindent 4 }}
    app.kubernetes.io/component: ssh
spec:
  type: {{ .Values.service.ssh.type }}
  ports:
    - port: {{ .Values.service.ssh.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
      {{- if and (eq .Values.service.ssh.type "NodePort") .Values.service.ssh.nodePort }}
      nodePort: {{ .Values.service.ssh.nodePort }}
      {{- end }}
  selector:
    {{- include "forgejo.selectorLabels" . | nindent 4 }}