secret:
  backend:
    # openssl rand -hex 32
    instanceSecret: "4361726e697461732c206c69746572616c6c79206d65616e696e6720226c6974"

backend:
  replicaCount: 1
  environment:
    - name: RUST_LOG
      value: "info"
  ingress:
    enabled: true
    className: "traefik" # Set to "nginx" if using NGINX Ingress Controller
    annotations: {
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure",
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    }
    tls: "convex-api-tls"
    hosts: api.convex.example.com
  resources:
    limits:
      cpu: 1
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  persistence:
    enabled: false
    storageClassName: "local-path"
    size: 10Gi

dashboard:
  replicaCount: 1
  ingress:
    enabled: true
    className: "traefik" # Set to "nginx" if using NGINX Ingress Controller
    annotations: {
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure",
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    }
    tls: "convex-dashboard-tls"
    hosts: dashboard.convex.example.com
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi