apiVersion: v1
kind: Secret
metadata:
  name: {{ include "convex.secret.backend" . }}
  labels:
    {{- include "convex.labels" . | nindent 4 }}
type: Opaque
data:
  instance_secret: {{- if .Values.secret.backend.instanceSecret }}
    {{ .Values.secret.backend.instanceSecret | b64enc | quote }}
  {{- else }}
    {{ printf "%x" (randBytes 32 | b64dec) | b64enc | quote }}
  {{- end }}