apiVersion: v1
kind: Secret
metadata:
  name: {{ include "convex.secret.backend" . }}
  labels:
    {{- include "convex.labels" . | nindent 4 }}
type: Opaque
data:
  instance_secret: {{ .Values.secret.backend.instanceSecret | b64enc }}