{{- if .Values.novnc.guest.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubevirt-vm.consoleName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubevirt-vm.consoleLabels" . | nindent 4 }}
spec:
  type: {{ .Values.novnc.service.type }}
  ports:
    - name: http
      port: {{ .Values.novnc.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "kubevirt-vm.consoleSelectorLabels" . | nindent 4 }}
{{- end }}
