{{- if .Values.novnc.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubevirt-vm.fullname" . }}-console
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubevirt-vm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubevirt-vm.fullname" . }}-console
subjects:
  - kind: ServiceAccount
    name: {{ include "kubevirt-vm.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
