apiVersion: v1
kind: Service
metadata:
  name: {{ include "picoclaw.fullname" . }}
  labels:
    {{- include "picoclaw.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.config.gateway.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "picoclaw.selectorLabels" . | nindent 4 }}
