apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dockur-windows.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dockur-windows.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.vm.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.vm.diskSize }}
