apiVersion: v1
kind: Service
metadata:
  name: {{ include "qemus-qemu.fullname" . }}-console
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qemus-qemu.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
spec:
  type: {{ .Values.console.service.type }}
  selector:
    {{- include "qemus-qemu.selectorLabels" . | nindent 4 }}
  ports:
    - name: console
      port: {{ .Values.console.service.port }}
      targetPort: console
      protocol: TCP
      {{- if and (eq .Values.console.service.type "NodePort") .Values.console.service.nodePort }}
      nodePort: {{ .Values.console.service.nodePort }}
      {{- end }}
{{- if .Values.ssh.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qemus-qemu.fullname" . }}-ssh
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qemus-qemu.labels" . | nindent 4 }}
    app.kubernetes.io/component: ssh
spec:
  type: {{ .Values.ssh.service.type }}
  selector:
    {{- include "qemus-qemu.selectorLabels" . | nindent 4 }}
  ports:
    - name: ssh
      port: {{ .Values.ssh.service.port }}
      targetPort: ssh
      protocol: TCP
      {{- if and (eq .Values.ssh.service.type "NodePort") .Values.ssh.service.nodePort }}
      nodePort: {{ .Values.ssh.service.nodePort }}
      {{- end }}
{{- end }}
